### ISSUE TITLE
References for catenable deques

### ISSUE THREAD

**Issue by duog** [ekmett/guanxi#5]
Hi,

I have very much enjoyed your videos on youtube, though I haven't been able to catch any live streams.

I was trying to understand your implementation of catenable deques in Unaligned.hs, but it doesn't seem to match any papers I could find. Would you be able to provide a reference?

**Comment by ekmett** [comment]
They are covered in Okasaki's book "Purely Functional Data Structures."

See section 7.2.1 ["Lists with efficient concatenation"](https://www.cs.cmu.edu/~rwh/theses/okasaki.pdf).
